# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
#忽略第三方库中的警告提示 （提示了也不能改😂）
inhibit_all_warnings!

target 'YLProject' do
    
pod 'CYLTabBarController', '~> 1.17.7' 
pod 'YYText', '~> 1.0.7'
pod 'YYCache', '~> 1.0.4'
pod 'YYModel','~> 1.0.4'
pod 'YTKNetwork', '~> 2.0.4'
pod 'SDWebImage', '~> 5.5.2'
pod 'Masonry','~> 1.1.0'
pod 'SVProgressHUD','~> 2.2.5'           #显示loading
pod 'IQKeyboardManager','~> 6.0.2'       #键盘偏移
pod 'FMDB','~> 2.7.2'
pod 'LKDBHelper', '~> 2.5.1'             #存储
pod 'SDCycleScrollView', '~> 1.80'       #轮播图
pod 'TYCyclePagerView','~> 1.1.0'        #卡片样式轮播
pod 'GVUserDefaults', '~> 1.0.2'         #userDefaults存储
pod 'MJRefresh', '~> 3.1.16'             #刷新
pod 'JLRoutes', '~> 2.1'                 #路由
pod 'WMPageController', '~> 2.5.2'       #多列表页面
pod 'LBXScan', '~> 2.3'                  #扫一扫
pod 'M13ProgressSuite', '~> 1.2.9'       #进度条
pod 'ActionSheetPicker-3.0', '~> 2.3.0'  #时间选择器
pod 'YLKits', '~> 0.0.4'
pod 'TZImagePickerController', '~> 3.2.5'#图片选择器
pod 'SAMKeychain', '~> 1.5.3'

#友盟相关
pod 'UMCCommon'
pod 'UMCCommonLog'
pod 'UMCAnalytics'
pod 'UMCSecurityPlugins'
pod 'UMCPush'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCShare/Social/ReducedSina'

#调试库
#调试接口
pod 'GYHttpMock', :configuration => ['Debug']
#显示类名
pod 'YLControllerName', :configuration => ['Debug']

#调试模式
pod 'DoraemonKit/Core', :configurations => ['Debug']
pod 'DoraemonKit/WithLogger', :configurations => ['Debug']
pod 'DoraemonKit/WithGPS', :configurations => ['Debug']
pod 'DoraemonKit/WithLoad', :configurations => ['Debug']
pod 'DoraemonKit/WithDatabase', :configurations => ['Debug']
pod 'DoraemonKit/WithMLeaksFinder', :configurations => ['Debug']
    
end
