# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
#忽略第三方库中的警告提示 （提示了也不能改😂）
inhibit_all_warnings!

target 'YLProject' do
    
pod 'CYLTabBarController', '~> 1.17.7'
pod 'YYText', '~> 1.0.7'
pod 'YYCache', '~> 1.0.4'
pod 'YYModel','~> 1.0.4'
pod 'YTKNetwork', '~> 2.0.4'
pod 'SDWebImage','~> 4.3.3'
pod 'Masonry','~> 1.1.0'
pod 'SVProgressHUD','~> 2.2.5'
pod 'IQKeyboardManager','~> 6.0.2'
pod 'FMDB','~> 2.7.2'
pod 'LKDBHelper', '~> 2.5.1'
pod 'TYCyclePagerView','~> 1.1.0'       #卡片样式轮播
pod 'GVUserDefaults', '~> 1.0.2'
pod 'WebViewJavascriptBridge', '~> 6.0'
pod 'MJRefresh', '~> 3.1.16'
pod 'HHRouter', '~> 0.1.9'              #路由
pod 'WMPageController', '~> 2.5.2'      #多列表页面
pod 'CocoaLumberjack', '~> 3.5.2'       #日志库
pod 'LBXScan', '~> 2.3'                 #扫一扫
pod 'M13ProgressSuite', '~> 1.2.9'      #进度条
pod 'ActionSheetPicker-3.0', '~> 2.3.0' #时间选择器

#调试库
pod 'GYHttpMock', '~> 1.0.0', :configuration => 'Debug'           #调试接口
pod 'YLControllerName', :configuration => 'Debug'                 #显示类名
pod 'MLeaksFinder', :configuration => 'Debug'                     #检测内存泄漏
pod 'DoraemonKit/Core', '~> 1.1.7', :configuration => 'Debug'     #调试模式
pod 'DoraemonKit/WithLogger', '~> 1.1.7', :configuration => 'Debug'
pod 'DoraemonKit/WithGPS', '~> 1.1.7', :configuration => 'Debug'
pod 'DoraemonKit/WithLoad', '~> 1.1.7', :configuration => 'Debug'
    
end
